# Generated by Django 3.1.7 on 2021-03-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev', models.CharField(max_length=100)),
                ('trans', models.CharField(max_length=100)),
                ('new', models.CharField(max_length=100)),
                ('voter', models.CharField(max_length=100)),
            ],
        ),
    ]
